#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(STRUGGLE_BUG) \
    F(X_SCISSOR) \
    F(DARK_PULSE) \
    F(FEINT_ATTACK) \
    F(FLATTER) \
    F(BREAKING_SWIPE) \
    F(DRAGON_TAIL) \
    F(ELECTROWEB) \
    F(SHOCK_WAVE) \
    F(THUNDERBOLT) \
    F(DRAINING_KISS) \
    F(MISTY_EXPLOSION) \
    F(PLAY_ROUGH) \
    F(AURA_SPHERE) \
    F(BODY_PRESS) \
    F(SEISMIC_TOSS) \
    F(FLAMETHROWER) \
    F(WILL_O_WISP) \
    F(AERIAL_ACE) \
    F(DEFOG) \
    F(DUAL_WINGBEAT) \
    F(ROOST) \
    F(TAILWIND) \
    F(CURSE) \
    F(NIGHT_SHADE) \
    F(SHADOW_BALL) \
    F(MAGICAL_LEAF) \
    F(SOLAR_BLADE) \
    F(SOLAR_BEAM) \
    F(EARTH_POWER) \
    F(EARTHQUAKE) \
    F(ICE_BEAM) \
    F(ICY_WIND) \
    F(EXPLOSION) \
    F(FACADE) \
    F(HYPER_VOICE) \
    F(SWAGGER) \
    F(ME_FIRST) \
    F(WEATHER_BALL) \
    F(SLUDGE_BOMB) \
    F(HEAL_PULSE) \
    F(PSYCHIC) \
    F(PSYCHIC_FANGS) \
    F(SKILL_SWAP) \
    F(ROCK_BLAST) \
    F(ROCK_TOMB) \
    F(FLASH_CANNON) \
    F(HEAVY_SLAM) \
    F(SMART_STRIKE) \
    F(LIFE_DEW)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
